#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    remove)
	if [ -e /etc/apache2/apache2.conf -a -e /etc/apache2/mods-enabled/php5.load ]; then
	    # set a flag to remember the original state useful when
	    # reinstalling the same version.
	    touch /etc/php5/apache2filter/.start
	fi
	if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
	    . /usr/share/apache2/apache2-maintscript-helper
	    apache2_invoke dismod php5filter
	fi
	;;
esac

exit 0
