#!/bin/sh

set -e

#DEBHELPER#


if [ "$1" != "configure" ]; then
    exit 0
fi

phpini="/etc/php5/apache/php.ini"

if ! [ -f $phpini ]; then
	mkdir -p /etc/php5/apache
	cp /usr/share/php5/php.ini-dist $phpini
fi

if [ -n "$2" ]; then
# we're upgrading. don't ask again
        exit 0
fi

for i in apache apache-ssl apache-perl; do
        if [ -e /etc/$i/httpd.conf ]; then
                apache-modconf $i enable mod_php5
        fi
done

exit 0
