#!/bin/sh

set -e

#DEBHELPER#

if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
    dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/php5_cgi.conf /etc/apache2/conf-available/php5-cgi.conf 5.5.0~beta4-1 -- "$@"
fi

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
    dpkg-maintscript-helper rm_conffile /etc/apache2/mods-available/php5_cgi.load
fi

exit 0
