#!/bin/sh

set -e

#EXTRA#

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if [ -e /usr/share/php5/php5-maintscript-helper ] ; then
	. /usr/share/php5/php5-maintscript-helper

	for dsoname in @modules@; do
	    inifile=${dsoname}.ini
	    priority=$(sed -ne "s/^; priority=\([0-9]\+\)$/\\1/p" /usr/share/php5/@package@/${inifile})
	    php5_invoke dismod ALL ${dsoname}/${priority:-20} restart
	done
    fi
fi

#DEBHELPER#

exit 0
